### ISSUE TITLE
Stripe Webhook Endpoint

### ISSUE THREAD

**Issue by KneesDev** [RicardoGEsteves/next-digital-marketplace#266]
So what's the Stripe webhook URL even supposed to be?

**Comment by RicardoGEsteves** [comment]
> So what's the Stripe webhook URL even supposed to be?

What do you mean? the API endpoint?

**Comment by KneesDev** [comment]
The Stripe dashboard requires a webhook endpoint to make the requests to when an event is occurred. What should be the URL that we need to enter? (e.g. <mydomain>/api/..)

**Comment by RicardoGEsteves** [comment]
> The Stripe dashboard requires a webhook endpoint to make the requests to when an event is occurred. What should be the URL that we need to enter? (e.g. mydomain.com/api/..)

It's up to you, you can define the route that fit your needs! I set to /api/webhooks/stripe.

**Comment by KneesDev** [comment]
Thanks!
